export const MESSAGE = {
  SYSTEM: {
    UNAUTHORIZED: 'Unauthorized!. User not found',
    SERVER_ERROR: 'Internal Server Error',
    NOT_FOUND: 'Not Found',
    BAD_REQUEST: 'Bad Request',
    FORBIDDEN: 'You are not allowed to perform this action',
    VALIDATE_ERROR: 'Validate error',
  },
  AUTH: {
    EMAIL_NOT_EXIST: "This email isn't exist",
    INVALID_CREDENTIAL: 'Username or password is not correct',
    PASSWORD_INCORRECT: 'Password is incorrect',
    INVALID_TOKEN: 'This token is not valid',
    INVALID_OTP: 'This OTP is not valid',
    ACCOUNT_NOT_VERIFY: 'Your account has not yet been verified.',
    ACCOUNT_NOT_ACTIVE: 'Your account has not yet been activated.',
    LOGIN_SUCCESSFUL: 'You are successfully logged in',
    LOGOUT_SUCCESSFUL: 'You are successfully logged out',
    REFRESH_TOKEN_SUCCESSFUL: 'User created a new refreshToken successfully',
    OTP_EXPIRE: 'OTP ExpiredError',
    TOKEN_EXPIRE: 'TOKEN ExpiredError',
  },
  USER: {
    CREATE_SUCCESSFUL: 'User created successfully',
    UPDATE_SUCCESSFUL: 'User updated successfully',
    UPDATE_UNSUCCESSFUL: 'User updated unsuccessfully',
    DELETE_SUCCESSFUL: 'User deleted successfully',
    ID_NOT_FOUND: "UserId didn't found in database",
    DETAIL: 'A detail of a User in database',
    LIST_ALL: 'A list of Users in database',
    EMAIL_ALREADY_TAKEN: 'This email is already taken',
    AVATAR_INVALID_EXTENSION:
      'Invalid Image. The Image must be a file of type: .jpeg, .jpg, .png, .gif',
  },
  UPLOAD: {
    FILE_SUCCESSFUL: 'A file uploaded successfully',
    FILE_UNSUCCESSFUL: 'A file uploaded unsuccessfully',
    FILE_LIMIT: 'A file size limit exceeded',
    FILE_INVALID:
      'This uploader is supposed to only accept png|jpg|jpeg|gif formats.',
    FILE_NO_CHOOSE: 'No file chosen',
    ID_NOT_FOUND: "UploadId didn't found in database",
  },
  EMAIL: {
    TEMPLATE_NAME_NOT_FOUND: 'template name not found',
    NOT_FOUND: 'Mail not found',
    SEND_SUCCESSFUL: 'Mail sent successfully',
    SEND_UNSUCCESSFUL: 'Mail sent unsuccessfully',
  },
  ROLE: {
    CREATE_SUCCESSFUL: 'Role created successfully',
    CREATE_UNSUCCESSFUL: 'Role created unsuccessfully',
    UPDATE_SUCCESSFUL: 'Role updated successfully',
    UPDATE_UNSUCCESSFUL: 'Role updated unsuccessfully',
    DELETE_SUCCESSFUL: 'Role deleted successfully',
    ID_NOT_FOUND: "RoleId didn't found in database",
    DETAIL: 'A detail of a Role in database',
    LIST_ALL: 'A list of Roles in database',
    NAME_IS_EXIST: 'This name is already taken',
  },
};
